# Advanced Feature Engineering

In [1]:
# Standard Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read in the data
data = pd.read_csv('./dataset/data.csv')

In [3]:
# Preview the first 5 rows
data.head()

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.73,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.42,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.95,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.64,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma

In [4]:
# Data Shape
data.shape

(91713, 186)

In [5]:
# Function to print NA in all the columns:
def print_na(df):
    for i in range(df.isna().sum().shape[0]):
        f = df.isna().sum().index[i]
        v = df.isna().sum()[i]
        print(f, " : ", v)

In [6]:
# Print the missing values
print_na(data)

encounter_id  :  0
patient_id  :  0
hospital_id  :  0
hospital_death  :  0
age  :  4228
bmi  :  3429
elective_surgery  :  0
ethnicity  :  1395
gender  :  25
height  :  1334
hospital_admit_source  :  21409
icu_admit_source  :  112
icu_id  :  0
icu_stay_type  :  0
icu_type  :  0
pre_icu_los_days  :  0
readmission_status  :  0
weight  :  2720
albumin_apache  :  54379
apache_2_diagnosis  :  1662
apache_3j_diagnosis  :  1101
apache_post_operative  :  0
arf_apache  :  715
bilirubin_apache  :  58134
bun_apache  :  19262
creatinine_apache  :  18853
fio2_apache  :  70868
gcs_eyes_apache  :  1901
gcs_motor_apache  :  1901
gcs_unable_apache  :  1037
gcs_verbal_apache  :  1901
glucose_apache  :  11036
heart_rate_apache  :  878
hematocrit_apache  :  19878
intubated_apache  :  715
map_apache  :  994
paco2_apache  :  70868
paco2_for_ph_apache  :  70868
pao2_apache  :  70868
ph_apache  :  70868
resprate_apache  :  1234
sodium_apache  :  18600
temp_apache  :  4108
urineoutput_apache  :  48998
ventilated_apache  :  715
wbc_apache  :  22012
d1_diasbp_invasive_max  :  67984
d1_diasbp_invasive_min  :  67984
d1_diasbp_max  :  165
d1_diasbp_min  :  165
d1_diasbp_noninvasive_max  :  1040
d1_diasbp_noninvasive_min  :  1040
d1_heartrate_max  :  145
d1_heartrate_min  :  145
d1_mbp_invasive_max  :  67777
d1_mbp_invasive_min  :  67777
d1_mbp_max  :  220
d1_mbp_min  :  220
d1_mbp_noninvasive_max  :  1479
d1_mbp_noninvasive_min  :  1479
d1_resprate_max  :  385
d1_resprate_min  :  385
d1_spo2_max  :  333
d1_spo2_min  :  333
d1_sysbp_invasive_max  :  67959
d1_sysbp_invasive_min  :  67959
d1_sysbp_max  :  159
d1_sysbp_min  :  159
d1_sysbp_noninvasive_max  :  1027
d1_sysbp_noninvasive_min  :  1027
d1_temp_max  :  2324
d1_temp_min  :  2324
h1_diasbp_invasive_max  :  74928
h1_diasbp_invasive_min  :  74928
h1_diasbp_max  :  3619
h1_diasbp_min  :  3619
h1_diasbp_noninvasive_max  :  7350
h1_diasbp_noninvasive_min  :  7350
h1_heartrate_max  :  2790
h1_heartrate_min  :  2790
h1_mbp_invasive_max  :  74844
h1_mbp_invasive_min  :  74844
h1_mbp_max  :  4639
h1_mbp_min  :  4639
h1_mbp_noninvasive_max  :  9084
h1_mbp_noninvasive_min  :  9084
h1_resprate_max  :  4357
h1_resprate_min  :  4357
h1_spo2_max  :  4185
h1_spo2_min  :  4185
h1_sysbp_invasive_max  :  74915
h1_sysbp_invasive_min  :  74915
h1_sysbp_max  :  3611
h1_sysbp_min  :  3611
h1_sysbp_noninvasive_max  :  7341
h1_sysbp_noninvasive_min  :  7341
h1_temp_max  :  21732
h1_temp_min  :  21732
d1_albumin_max  :  49096
d1_albumin_min  :  49096
d1_bilirubin_max  :  53673
d1_bilirubin_min  :  53673
d1_bun_max  :  10514
d1_bun_min  :  10514
d1_calcium_max  :  13069
d1_calcium_min  :  13069
d1_creatinine_max  :  10169
d1_creatinine_min  :  10169
d1_glucose_max  :  5807
d1_glucose_min  :  5807
d1_hco3_max  :  15071
d1_hco3_min  :  15071
d1_hemaglobin_max  :  12147
d1_hemaglobin_min  :  12147
d1_hematocrit_max  :  11654
d1_hematocrit_min  :  11654
d1_inr_max  :  57941
d1_inr_min  :  57941
d1_lactate_max  :  68396
d1_lactate_min  :  68396
d1_platelets_max  :  13444
d1_platelets_min  :  13444
d1_potassium_max  :  9585
d1_potassium_min  :  9585
d1_sodium_max  :  10195
d1_sodium_min  :  10195
d1_wbc_max  :  13174
d1_wbc_min  :  13174
h1_albumin_max  :  83824
h1_albumin_min  :  83824
h1_bilirubin_max  :  84619
h1_bilirubin_min  :  84619
h1_bun_max  :  75091
h1_bun_min  :  75091
h1_calcium_max  :  75863
h1_calcium_min  :  75863
h1_creatinine_max  :  74957
h1_creatinine_min  :  74957
h1_glucose_max  :  52614
h1_glucose_min  :  52614
h1_hco3_max  :  76094
h1_hco3_min  :  76094
h1_hemaglobin_max  :  73123
h1_hemaglobin_min  :  73123
h1_hematocrit_max  :  73420
h1_hematocrit_min  :  73420
h1_inr_max  :  57941
h1_inr_min  :  57941
h1_lactate_max  :  84369
h1_lactate_min  :  84369
h1_platelets_max  :  75673
h1_platelets_min  :  75673
h1_potassium_max  :  72102
h1_potassium_min  :  72102
h1_sodium_max  :  72617
h1_sodium_min  :  72617
h1_wbc_max  :  75953
h1_wbc_min  :  75953
d1_arterial_pco2_max  :  59271
d1_arterial_pco2_min  :  59271
d1_arterial_ph_max  :  60123
d1_arterial_ph_min  :  60123
d1_arterial_po2_max  :  59262
d1_arterial_po2_min  :  59262
d1_pao2fio2ratio_max  :  66008
d1_pao2fio2ratio_min  :  66008
h1_arterial_pco2_max  :  75959
h1_arterial_pco2_min  :  75959
h1_arterial_ph_max  :  76424
h1_arterial_ph_min  :  76424
h1_arterial_po2_max  :  75945
h1_arterial_po2_min  :  75945
h1_pao2fio2ratio_max  :  80195
h1_pao2fio2ratio_min  :  80195
apache_4a_hospital_death_prob  :  7947
apache_4a_icu_death_prob  :  7947
aids  :  715
cirrhosis  :  715
diabetes_mellitus  :  715
hepatic_failure  :  715
immunosuppression  :  715
leukemia  :  715
lymphoma  :  715
solid_tumor_with_metastasis  :  715
apache_3j_bodysystem  :  1662
apache_2_bodysystem  :  1662

In [7]:
data.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91713 entries, 0 to 91712
Data columns (total 186 columns):
 #   Column                         Dtype
---  ------                         -----
 0   encounter_id                   int64
 1   patient_id                     int64
 2   hospital_id                    int64
 3   hospital_death                 int64
 4   age                            float64
 5   bmi                            float64
 6   elective_surgery               int64
 7   ethnicity                      object
 8   gender                         object
 9   height                         float64
 10  hospital_admit_source          object
 11  icu_admit_source               object
 12  icu_id                         int64
 13  icu_stay_type                  object
 14  icu_type                       object
 15  pre_icu_los_days               float64
 16  readmission_status             int64
 17  weight                         float64
 18  albumin_apache                 float64
 19  apache_2_diagnosis             float64
 20  apache_3j_diagnosis            float64
 21  apache_post_operative          int64
 22  arf_apache                     float64
 23  bilirubin_apache               float64
 24  bun_apache                     float64
 25  creatinine_apache              float64
 26  fio2_apache                    float64
 27  gcs_eyes_apache                float64
 28  gcs_motor_apache               float64
 29  gcs_unable_apache              float64
 30  gcs_verbal_apache              float64
 31  glucose_apache                 float64
 32  heart_rate_apache              float64
 33  hematocrit_apache              float64
 34  intubated_apache               float64
 35  map_apache                     float64
 36  paco2_apache                   float64
 37  paco2_for_ph_apache            float64
 38  pao2_apache                    float64
 39  ph_apache                      float64
 40  resprate_apache                float64
 41  sodium_apache                  float64
 42  temp_apache                    float64
 43  urineoutput_apache             float64
 44  ventilated_apache              float64
 45  wbc_apache                     float64
 46  d1_diasbp_invasive_max         float64
 47  d1_diasbp_invasive_min         float64
 48  d1_diasbp_max                  float64
 49  d1_diasbp_min                  float64
 50  d1_diasbp_noninvasive_max      float64
 51  d1_diasbp_noninvasive_min      float64
 52  d1_heartrate_max               float64
 53  d1_heartrate_min               float64
 54  d1_mbp_invasive_max            float64
 55  d1_mbp_invasive_min            float64
 56  d1_mbp_max                     float64
 57  d1_mbp_min                     float64
 58  d1_mbp_noninvasive_max         float64
 59  d1_mbp_noninvasive_min         float64
 60  d1_resprate_max                float64
 61  d1_resprate_min                float64
 62  d1_spo2_max                    float64
 63  d1_spo2_min                    float64
 64  d1_sysbp_invasive_max          float64
 65  d1_sysbp_invasive_min          float64
 66  d1_sysbp_max                   float64
 67  d1_sysbp_min                   float64
 68  d1_sysbp_noninvasive_max       float64
 69  d1_sysbp_noninvasive_min       float64
 70  d1_temp_max                    float64
 71  d1_temp_min                    float64
 72  h1_diasbp_invasive_max         float64
 73  h1_diasbp_invasive_min         float64
 74  h1_diasbp_max                  float64
 75  h1_diasbp_min                  float64
 76  h1_diasbp_noninvasive_max      float64
 77  h1_diasbp_noninvasive_min      float64
 78  h1_heartrate_max               float64
 79  h1_heartrate_min               float64
 80  h1_mbp_invasive_max            float64
 81  h1_mbp_invasive_min            float64
 82  h1_mbp_max                     float64
 83  h1_mbp_min                     float64
 84  h1_mbp_noninvasive_max         float64
 85  h1_mbp_noninvasive_min         float64
 86  h1_resprate_max                float64
 87  h1_resprate_min                float64
 88  h1_spo2_max                    float64
 89  h1_spo2_min                    float64
 90  h1_sysbp_invasive_max          float64
 91  h1_sysbp_invasive_min          float64
 92  h1_sysbp_max                   float64
 93  h1_sysbp_min                   float64
 94  h1_sysbp_noninvasive_max       float64
 95  h1_sysbp_noninvasive_min       float64
 96  h1_temp_max                    float64
 97  h1_temp_min                    float64
 98  d1_albumin_max                 float64
 99  d1_albumin_min                 float64
 100 d1_bilirubin_max               float64
 101 d1_bilirubin_min               float64
 102 d1_bun_max                     float64
 103 d1_bun_min                     float64
 104 d1_calcium_max                 float64
 105 d1_calcium_min                 float64
 106 d1_creatinine_max              float64
 107 d1_creatinine_min              float64
 108 d1_glucose_max                 float64
 109 d1_glucose_min                 float64
 110 d1_hco3_max                    float64
 111 d1_hco3_min                    float64
 112 d1_hemaglobin_max              float64
 113 d1_hemaglobin_min              float64
 114 d1_hematocrit_max              float64
 115 d1_hematocrit_min              float64
 116 d1_inr_max                     float64
 117 d1_inr_min                     float64
 118 d1_lactate_max                 float64
 119 d1_lactate_min                 float64
 120 d1_platelets_max               float64
 121 d1_platelets_min               float64
 122 d1_potassium_max               float64
 123 d1_potassium_min               float64
 124 d1_sodium_max                  float64
 125 d1_sodium_min                  float64
 126 d1_wbc_max                     float64
 127 d1_wbc_min                     float64
 128 h1_albumin_max                 float64
 129 h1_albumin_min                 float64
 130 h1_bilirubin_max               float64
 131 h1_bilirubin_min               float64
 132 h1_bun_max                     float64
 133 h1_bun_min                     float64
 134 h1_calcium_max                 float64
 135 h1_calcium_min                 float64
 136 h1_creatinine_max              float64
 137 h1_creatinine_min              float64
 138 h1_glucose_max                 float64
 139 h1_glucose_min                 float64
 140 h1_hco3_max                    float64
 141 h1_hco3_min                    float64
 142 h1_hemaglobin_max              float64
 143 h1_hemaglobin_min              float64
 144 h1_hematocrit_max              float64
 145 h1_hematocrit_min              float64
 146 h1_inr_max                     float64
 147 h1_inr_min                     float64
 148 h1_lactate_max                 float64
 149 h1_lactate_min                 float64
 150 h1_platelets_max               float64
 151 h1_platelets_min               float64
 152 h1_potassium_max               float64
 153 h1_potassium_min               float64
 154 h1_sodium_max                  float64
 155 h1_sodium_min                  float64
 156 h1_wbc_max                     float64
 157 h1_wbc_min                     float64
 158 d1_arterial_pco2_max           float64
 159 d1_arterial_pco2_min           float64
 160 d1_arterial_ph_max             float64
 161 d1_arterial_ph_min             float64
 162 d1_arterial_po2_max            float64
 163 d1_arterial_po2_min            float64
 164 d1_pao2fio2ratio_max           float64
 165 d1_pao2fio2ratio_min           float64
 166 h1_arterial_pco2_max           float64
 167 h1_arterial_pco2_min           float64
 168 h1_arterial_ph_max             float64
 169 h1_arterial_ph_min             float64
 170 h1_arterial_po2_max            float64
 171 h1_arterial_po2_min            float64
 172 h1_pao2fio2ratio_max           float64
 173 h1_pao2fio2ratio_min           float64
 174 apache_4a_hospital_death_prob  float64
 175 apache_4a_icu_death_prob       float64
 176 aids                           float64
 177 cirrhosis                      float64
 178 diabetes_mellitus              float64
 179 hepatic_failure                float64
 180 immunosuppression              float64
 181 leukemia                       float64
 182 lymphoma                       float64
 183 solid_tumor_with_metastasis    float64
 184 apache_3j_bodysystem           object
 185 apache_2_bodysystem            object
dtypes: float64(170), int64(8), object(8)
memory usage: 130.1+ MB

In [8]:
# Summary statistics
data.describe()

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,height,icu_id,pre_icu_los_days,...,apache_4a_hospital_death_prob,apache_4a_icu_death_prob,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
count,91713.000000,91713.000000,91713.000000,91713.000000,87485.000000,88284.000000,91713.000000,90379.000000,91713.000000,91713.000000,...,83766.000000,83766.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000
mean,65606.079280,65537.131464,105.669262,0.086302,62.309516,29.185818,0.183736,169.641588,508.357692,0.835766,...,0.086787,0.043955,0.000857,0.015693,0.225192,0.012989,0.026165,0.007066,0.004132,0.020638
std,37795.088538,37811.252183,62.854406,0.280811,16.775119,8.275142,0.387271,10.795378,228.989661,2.487756,...,0.247569,0.217341,0.029265,0.124284,0.417711,0.113229,0.159628,0.083763,0.064148,0.142169
min,1.000000,1.000000,2.000000,0.000000,16.000000,14.844926,0.000000,137.200000,82.000000,-24.947222,...,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32852.000000,32830.000000,47.000000,0.000000,52.000000,23.641975,0.000000,162.500000,369.000000,0.035417,...,0.020000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,65665.000000,65413.000000,109.000000,0.000000,65.000000,27.654655,0.000000,170.100000,504.000000,0.138889,...,0.050000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,98342.000000,98298.000000,161.000000,0.000000,75.000000,32.930206,0.000000,177.800000,679.000000,0.409028,...,0.130000,0.060000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,131051.000000,131051.000000,204.000000,1.000000,89.000000,67.814990,1.000000,195.590000,927.000000,159.090972,...,0.990000,0.970000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
# Age
data['age'].isna().sum()

4228

In [10]:
# Age
data['age'] = data['age'].fillna(data['age'].median())

In [11]:
# Height
data['height'] = data['height'].fillna(data['height'].median())

In [12]:
# Weight
data['weight'] = data['weight'].fillna(data['weight'].median())

In [13]:
# Body mass index
data['body_mass_index'] = data['weight'] / ((data['height']**2)/(100**2))

In [14]:
# data['body_mass_index'] = pd.cut(data['body_mass_index'], 8)

In [15]:
# Fine classing for the Body Mass Index
data['body_mass_index:<15'] = np.where(data['body_mass_index'].isin(range(15)), 1, 0)
data['body_mass_index:>15 and <=16'] = np.where(data['body_mass_index'].isin(range(15,17)), 1,0)
data['body_mass_index:>16 and <=19'] = np.where(data['body_mass_index'].isin(range(16,20)), 1,0)
data['body_mass_index:>19 and <=25'] = np.where(data['body_mass_index'].isin(range(19,26)), 1,0)
data['body_mass_index:>25 and <=30'] = np.where(data['body_mass_index'].isin(range(26,31)), 1,0)
data['body_mass_index:>30 and <=35'] = np.where(data['body_mass_index'].isin(range(31,36)), 1,0)
data['body_mass_index:>35 and <=40'] = np.where(data['body_mass_index'].isin(range(36,41)), 1,0)
data['body_mass_index:>40'] = np.where(data['body_mass_index'].isin(range(40)), 1, 0)

In [16]:
# pre_icu_los_days
data['IsUrgent'] = np.where(data['pre_icu_los_days'] <= (2/24), 1, 0)

In [17]:
data['apache_4a_icu_death_prob'].isna().sum()

7947

In [18]:
# apache_4a_icu_death_prob
data['apache_4a_icu_death_prob'] = data['apache_4a_icu_death_prob']. replace({-1:0})

In [19]:
# Fill NA with 0
data['apache_4a_icu_death_prob'] = data['apache_4a_icu_death_prob'].fillna(0)

In [20]:
# Check to see if any missing numbers
data['apache_4a_icu_death_prob'].isna().sum()

0

In [21]:
# apache_4a_hospital_death_prob
data['apache_4a_hospital_death_prob'] = data['apache_4a_hospital_death_prob'].replace({-1, 0})

In [22]:
# Fill NA with 0
data['apache_4a_hospital_death_prob'] = data['apache_4a_hospital_death_prob'].fillna(0)

In [23]:
# Create a new column max_apache_4a_death_prob
data['max_apache_4a_death_prob'] = data[['apache_4a_hospital_death_prob', 'apache_4a_icu_death_prob']].max(axis = 1)

In [24]:
# Check the amount of remaining missing values
print_na(data)

encounter_id  :  0
patient_id  :  0
hospital_id  :  0
hospital_death  :  0
age  :  0
bmi  :  3429
elective_surgery  :  0
ethnicity  :  1395
gender  :  25
height  :  0
hospital_admit_source  :  21409
icu_admit_source  :  112
icu_id  :  0
icu_stay_type  :  0
icu_type  :  0
pre_icu_los_days  :  0
readmission_status  :  0
weight  :  0
albumin_apache  :  54379
apache_2_diagnosis  :  1662
apache_3j_diagnosis  :  1101
apache_post_operative  :  0
arf_apache  :  715
bilirubin_apache  :  58134
bun_apache  :  19262
creatinine_apache  :  18853
fio2_apache  :  70868
gcs_eyes_apache  :  1901
gcs_motor_apache  :  1901
gcs_unable_apache  :  1037
gcs_verbal_apache  :  1901
glucose_apache  :  11036
heart_rate_apache  :  878
hematocrit_apache  :  19878
intubated_apache  :  715
map_apache  :  994
paco2_apache  :  70868
paco2_for_ph_apache  :  70868
pao2_apache  :  70868
ph_apache  :  70868
resprate_apache  :  1234
sodium_apache  :  18600
temp_apache  :  4108
urineoutput_apache  :  48998
ventilated_apache  :  715
wbc_apache  :  22012
d1_diasbp_invasive_max  :  67984
d1_diasbp_invasive_min  :  67984
d1_diasbp_max  :  165
d1_diasbp_min  :  165
d1_diasbp_noninvasive_max  :  1040
d1_diasbp_noninvasive_min  :  1040
d1_heartrate_max  :  145
d1_heartrate_min  :  145
d1_mbp_invasive_max  :  67777
d1_mbp_invasive_min  :  67777
d1_mbp_max  :  220
d1_mbp_min  :  220
d1_mbp_noninvasive_max  :  1479
d1_mbp_noninvasive_min  :  1479
d1_resprate_max  :  385
d1_resprate_min  :  385
d1_spo2_max  :  333
d1_spo2_min  :  333
d1_sysbp_invasive_max  :  67959
d1_sysbp_invasive_min  :  67959
d1_sysbp_max  :  159
d1_sysbp_min  :  159
d1_sysbp_noninvasive_max  :  1027
d1_sysbp_noninvasive_min  :  1027
d1_temp_max  :  2324
d1_temp_min  :  2324
h1_diasbp_invasive_max  :  74928
h1_diasbp_invasive_min  :  74928
h1_diasbp_max  :  3619
h1_diasbp_min  :  3619
h1_diasbp_noninvasive_max  :  7350
h1_diasbp_noninvasive_min  :  7350
h1_heartrate_max  :  2790
h1_heartrate_min  :  2790
h1_mbp_invasive_max  :  74844
h1_mbp_invasive_min  :  74844
h1_mbp_max  :  4639
h1_mbp_min  :  4639
h1_mbp_noninvasive_max  :  9084
h1_mbp_noninvasive_min  :  9084
h1_resprate_max  :  4357
h1_resprate_min  :  4357
h1_spo2_max  :  4185
h1_spo2_min  :  4185
h1_sysbp_invasive_max  :  74915
h1_sysbp_invasive_min  :  74915
h1_sysbp_max  :  3611
h1_sysbp_min  :  3611
h1_sysbp_noninvasive_max  :  7341
h1_sysbp_noninvasive_min  :  7341
h1_temp_max  :  21732
h1_temp_min  :  21732
d1_albumin_max  :  49096
d1_albumin_min  :  49096
d1_bilirubin_max  :  53673
d1_bilirubin_min  :  53673
d1_bun_max  :  10514
d1_bun_min  :  10514
d1_calcium_max  :  13069
d1_calcium_min  :  13069
d1_creatinine_max  :  10169
d1_creatinine_min  :  10169
d1_glucose_max  :  5807
d1_glucose_min  :  5807
d1_hco3_max  :  15071
d1_hco3_min  :  15071
d1_hemaglobin_max  :  12147
d1_hemaglobin_min  :  12147
d1_hematocrit_max  :  11654
d1_hematocrit_min  :  11654
d1_inr_max  :  57941
d1_inr_min  :  57941
d1_lactate_max  :  68396
d1_lactate_min  :  68396
d1_platelets_max  :  13444
d1_platelets_min  :  13444
d1_potassium_max  :  9585
d1_potassium_min  :  9585
d1_sodium_max  :  10195
d1_sodium_min  :  10195
d1_wbc_max  :  13174
d1_wbc_min  :  13174
h1_albumin_max  :  83824
h1_albumin_min  :  83824
h1_bilirubin_max  :  84619
h1_bilirubin_min  :  84619
h1_bun_max  :  75091
h1_bun_min  :  75091
h1_calcium_max  :  75863
h1_calcium_min  :  75863
h1_creatinine_max  :  74957
h1_creatinine_min  :  74957
h1_glucose_max  :  52614
h1_glucose_min  :  52614
h1_hco3_max  :  76094
h1_hco3_min  :  76094
h1_hemaglobin_max  :  73123
h1_hemaglobin_min  :  73123
h1_hematocrit_max  :  73420
h1_hematocrit_min  :  73420
h1_inr_max  :  57941
h1_inr_min  :  57941
h1_lactate_max  :  84369
h1_lactate_min  :  84369
h1_platelets_max  :  75673
h1_platelets_min  :  75673
h1_potassium_max  :  72102
h1_potassium_min  :  72102
h1_sodium_max  :  72617
h1_sodium_min  :  72617
h1_wbc_max  :  75953
h1_wbc_min  :  75953
d1_arterial_pco2_max  :  59271
d1_arterial_pco2_min  :  59271
d1_arterial_ph_max  :  60123
d1_arterial_ph_min  :  60123
d1_arterial_po2_max  :  59262
d1_arterial_po2_min  :  59262
d1_pao2fio2ratio_max  :  66008
d1_pao2fio2ratio_min  :  66008
h1_arterial_pco2_max  :  75959
h1_arterial_pco2_min  :  75959
h1_arterial_ph_max  :  76424
h1_arterial_ph_min  :  76424
h1_arterial_po2_max  :  75945
h1_arterial_po2_min  :  75945
h1_pao2fio2ratio_max  :  80195
h1_pao2fio2ratio_min  :  80195
apache_4a_hospital_death_prob  :  0
apache_4a_icu_death_prob  :  0
aids  :  715
cirrhosis  :  715
diabetes_mellitus  :  715
hepatic_failure  :  715
immunosuppression  :  715
leukemia  :  715
lymphoma  :  715
solid_tumor_with_metastasis  :  715
apache_3j_bodysystem  :  1662
apache_2_bodysystem  :  1662
body_mass_index  :  0
body_mass_index:<15  :  0
body_mass_index:>15 and <=16  :  0
body_mass_index:>16 and <=19  :  0
body_mass_index:>19 and <=25  :  0
body_mass_index:>25 and <=30  :  0
body_mass_index:>30 and <=35  :  0
body_mass_index:>35 and <=40  :  0
body_mass_index:>40  :  0
IsUrgent  :  0
max_apache_4a_death_prob  :  0

In [25]:
data.shape

(91713, 197)

In [26]:
# Drop columns of the dataframe if 90% of the column is NAN
data_90 = data.loc[:, data.isnull().mean() < .9]

In [27]:
data_90.shape

(91713, 191)

In [28]:
print_na(data_90)

encounter_id  :  0
patient_id  :  0
hospital_id  :  0
hospital_death  :  0
age  :  0
bmi  :  3429
elective_surgery  :  0
ethnicity  :  1395
gender  :  25
height  :  0
hospital_admit_source  :  21409
icu_admit_source  :  112
icu_id  :  0
icu_stay_type  :  0
icu_type  :  0
pre_icu_los_days  :  0
readmission_status  :  0
weight  :  0
albumin_apache  :  54379
apache_2_diagnosis  :  1662
apache_3j_diagnosis  :  1101
apache_post_operative  :  0
arf_apache  :  715
bilirubin_apache  :  58134
bun_apache  :  19262
creatinine_apache  :  18853
fio2_apache  :  70868
gcs_eyes_apache  :  1901
gcs_motor_apache  :  1901
gcs_unable_apache  :  1037
gcs_verbal_apache  :  1901
glucose_apache  :  11036
heart_rate_apache  :  878
hematocrit_apache  :  19878
intubated_apache  :  715
map_apache  :  994
paco2_apache  :  70868
paco2_for_ph_apache  :  70868
pao2_apache  :  70868
ph_apache  :  70868
resprate_apache  :  1234
sodium_apache  :  18600
temp_apache  :  4108
urineoutput_apache  :  48998
ventilated_apache  :  715
wbc_apache  :  22012
d1_diasbp_invasive_max  :  67984
d1_diasbp_invasive_min  :  67984
d1_diasbp_max  :  165
d1_diasbp_min  :  165
d1_diasbp_noninvasive_max  :  1040
d1_diasbp_noninvasive_min  :  1040
d1_heartrate_max  :  145
d1_heartrate_min  :  145
d1_mbp_invasive_max  :  67777
d1_mbp_invasive_min  :  67777
d1_mbp_max  :  220
d1_mbp_min  :  220
d1_mbp_noninvasive_max  :  1479
d1_mbp_noninvasive_min  :  1479
d1_resprate_max  :  385
d1_resprate_min  :  385
d1_spo2_max  :  333
d1_spo2_min  :  333
d1_sysbp_invasive_max  :  67959
d1_sysbp_invasive_min  :  67959
d1_sysbp_max  :  159
d1_sysbp_min  :  159
d1_sysbp_noninvasive_max  :  1027
d1_sysbp_noninvasive_min  :  1027
d1_temp_max  :  2324
d1_temp_min  :  2324
h1_diasbp_invasive_max  :  74928
h1_diasbp_invasive_min  :  74928
h1_diasbp_max  :  3619
h1_diasbp_min  :  3619
h1_diasbp_noninvasive_max  :  7350
h1_diasbp_noninvasive_min  :  7350
h1_heartrate_max  :  2790
h1_heartrate_min  :  2790
h1_mbp_invasive_max  :  74844
h1_mbp_invasive_min  :  74844
h1_mbp_max  :  4639
h1_mbp_min  :  4639
h1_mbp_noninvasive_max  :  9084
h1_mbp_noninvasive_min  :  9084
h1_resprate_max  :  4357
h1_resprate_min  :  4357
h1_spo2_max  :  4185
h1_spo2_min  :  4185
h1_sysbp_invasive_max  :  74915
h1_sysbp_invasive_min  :  74915
h1_sysbp_max  :  3611
h1_sysbp_min  :  3611
h1_sysbp_noninvasive_max  :  7341
h1_sysbp_noninvasive_min  :  7341
h1_temp_max  :  21732
h1_temp_min  :  21732
d1_albumin_max  :  49096
d1_albumin_min  :  49096
d1_bilirubin_max  :  53673
d1_bilirubin_min  :  53673
d1_bun_max  :  10514
d1_bun_min  :  10514
d1_calcium_max  :  13069
d1_calcium_min  :  13069
d1_creatinine_max  :  10169
d1_creatinine_min  :  10169
d1_glucose_max  :  5807
d1_glucose_min  :  5807
d1_hco3_max  :  15071
d1_hco3_min  :  15071
d1_hemaglobin_max  :  12147
d1_hemaglobin_min  :  12147
d1_hematocrit_max  :  11654
d1_hematocrit_min  :  11654
d1_inr_max  :  57941
d1_inr_min  :  57941
d1_lactate_max  :  68396
d1_lactate_min  :  68396
d1_platelets_max  :  13444
d1_platelets_min  :  13444
d1_potassium_max  :  9585
d1_potassium_min  :  9585
d1_sodium_max  :  10195
d1_sodium_min  :  10195
d1_wbc_max  :  13174
d1_wbc_min  :  13174
h1_bun_max  :  75091
h1_bun_min  :  75091
h1_calcium_max  :  75863
h1_calcium_min  :  75863
h1_creatinine_max  :  74957
h1_creatinine_min  :  74957
h1_glucose_max  :  52614
h1_glucose_min  :  52614
h1_hco3_max  :  76094
h1_hco3_min  :  76094
h1_hemaglobin_max  :  73123
h1_hemaglobin_min  :  73123
h1_hematocrit_max  :  73420
h1_hematocrit_min  :  73420
h1_inr_max  :  57941
h1_inr_min  :  57941
h1_platelets_max  :  75673
h1_platelets_min  :  75673
h1_potassium_max  :  72102
h1_potassium_min  :  72102
h1_sodium_max  :  72617
h1_sodium_min  :  72617
h1_wbc_max  :  75953
h1_wbc_min  :  75953
d1_arterial_pco2_max  :  59271
d1_arterial_pco2_min  :  59271
d1_arterial_ph_max  :  60123
d1_arterial_ph_min  :  60123
d1_arterial_po2_max  :  59262
d1_arterial_po2_min  :  59262
d1_pao2fio2ratio_max  :  66008
d1_pao2fio2ratio_min  :  66008
h1_arterial_pco2_max  :  75959
h1_arterial_pco2_min  :  75959
h1_arterial_ph_max  :  76424
h1_arterial_ph_min  :  76424
h1_arterial_po2_max  :  75945
h1_arterial_po2_min  :  75945
h1_pao2fio2ratio_max  :  80195
h1_pao2fio2ratio_min  :  80195
apache_4a_hospital_death_prob  :  0
apache_4a_icu_death_prob  :  0
aids  :  715
cirrhosis  :  715
diabetes_mellitus  :  715
hepatic_failure  :  715
immunosuppression  :  715
leukemia  :  715
lymphoma  :  715
solid_tumor_with_metastasis  :  715
apache_3j_bodysystem  :  1662
apache_2_bodysystem  :  1662
body_mass_index  :  0
body_mass_index:<15  :  0
body_mass_index:>15 and <=16  :  0
body_mass_index:>16 and <=19  :  0
body_mass_index:>19 and <=25  :  0
body_mass_index:>25 and <=30  :  0
body_mass_index:>30 and <=35  :  0
body_mass_index:>35 and <=40  :  0
body_mass_index:>40  :  0
IsUrgent  :  0
max_apache_4a_death_prob  :  0

In [28]:
# Dummify Ethnicity column
df = data_90['ethnicity']
ethnicity = pd.get_dummies(df, drop_first = True, prefix = 'ethnicity')

In [29]:
# Dummify the Gender column
df = data_90['gender']
gender = pd.get_dummies(df, drop_first = True, prefix = 'gender')

In [30]:
# Dummify the icu_admit_source
df = data['icu_admit_source']
icu_admit_source= pd.get_dummies(df, drop_first = True, prefix = 'icu_admit_source')

In [31]:
# Dummify the icu_type
df = data_90['icu_type']
icu_type = pd.get_dummies(df, drop_first = True, prefix = 'icu_type')

In [32]:
# Dummify the apache_2_bodysystem
df = data_90['apache_2_bodysystem']
apache_2_bodysystem = pd.get_dummies(df, drop_first = True, prefix = 'apache_2_bodysystem')

In [33]:
# Dummify the apache_3j_bodysystem
df = data_90['apache_3j_bodysystem']
apache_3j_bodysystem= pd.get_dummies(df, drop_first = True, prefix = 'apache_3j_bodysystem')

In [34]:
# Dummify Hospital Admit Source
df = data['hospital_admit_source']
hospital_admit_source = pd.get_dummies(df, drop_first = True, prefix = 'hospital_admit_source')

In [35]:
# Dummify the ICU stay type
df = data_90['icu_stay_type']
icu_stay_type = pd.get_dummies(df, drop_first = True, prefix = 'icu_stay_type')

In [36]:
# Concatenate all dummified columns with original reduced dataframe
data_new = pd.concat([data_90, ethnicity, gender, 
                  icu_stay_type, icu_admit_source, 
                  icu_type, apache_2_bodysystem, apache_3j_bodysystem, hospital_admit_source], axis = 1)

In [37]:
data_new.head()

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,hospital_admit_source_ICU,hospital_admit_source_ICU to SDU,hospital_admit_source_Observation,hospital_admit_source_Operating Room,hospital_admit_source_Other,hospital_admit_source_Other Hospital,hospital_admit_source_Other ICU,hospital_admit_source_PACU,hospital_admit_source_Recovery Room,hospital_admit_source_Step-Down Unit (SDU)
0,66154,25312,118,0,68.0,22.73,0,Caucasian,M,180.3,...,0,0,0,0,0,0,0,0,0,0
1,114252,59342,81,0,77.0,27.42,0,Caucasian,F,160.0,...,0,0,0,0,0,0,0,0,0,0
2,119783,50777,118,0,25.0,31.95,0,Caucasian,F,172.7,...,0,0,0,0,0,0,0,0,0,0
3,79267,46918,118,0,81.0,22.64,1,Caucasian,F,165.1,...,0,0,0,1,0,0,0,0,0,0
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
# Drop columns which were used to create new features and irrelevant columns
data_save = data_new.drop(columns = ['encounter_id', 'patient_id', 'hospital_id', 'weight', 'bmi', 'ethnicity',
                    'gender', 'icu_stay_type', 'icu_admit_source', 'icu_type', 'apache_2_bodysystem', 'apache_3j_bodysystem',
                               'hospital_admit_source', 'pre_icu_los_days', 'icu_id'], axis = 1)

In [39]:
# Preview new data frame
data_save.head()

,hospital_death,age,elective_surgery,height,readmission_status,albumin_apache,apache_2_diagnosis,apache_3j_diagnosis,apache_post_operative,arf_apache,...,hospital_admit_source_ICU,hospital_admit_source_ICU to SDU,hospital_admit_source_Observation,hospital_admit_source_Operating Room,hospital_admit_source_Other,hospital_admit_source_Other Hospital,hospital_admit_source_Other ICU,hospital_admit_source_PACU,hospital_admit_source_Recovery Room,hospital_admit_source_Step-Down Unit (SDU)
0,0,68.0,0,180.3,0,2.3,113.0,502.01,0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,0,77.0,0,160.0,0,NaN,108.0,203.01,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,0,25.0,0,172.7,0,NaN,122.0,703.03,0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,0,81.0,1,165.1,0,NaN,203.0,1206.03,1,0.0,...,0,0,0,1,0,0,0,0,0,0
4,0,19.0,0,188.0,0,NaN,119.0,601.01,0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
# Fill every column with its most frequent value
data_save = data_save.apply(lambda x:x.fillna(x.value_counts().index[0]))

In [47]:
# Print NA values to see if any still exist in the final dataframe
print_na(data_save)

hospital_death  :  0
age  :  0
elective_surgery  :  0
height  :  0
readmission_status  :  0
albumin_apache  :  0
apache_2_diagnosis  :  0
apache_3j_diagnosis  :  0
apache_post_operative  :  0
arf_apache  :  0
bilirubin_apache  :  0
bun_apache  :  0
creatinine_apache  :  0
fio2_apache  :  0
gcs_eyes_apache  :  0
gcs_motor_apache  :  0
gcs_unable_apache  :  0
gcs_verbal_apache  :  0
glucose_apache  :  0
heart_rate_apache  :  0
hematocrit_apache  :  0
intubated_apache  :  0
map_apache  :  0
paco2_apache  :  0
paco2_for_ph_apache  :  0
pao2_apache  :  0
ph_apache  :  0
resprate_apache  :  0
sodium_apache  :  0
temp_apache  :  0
urineoutput_apache  :  0
ventilated_apache  :  0
wbc_apache  :  0
d1_diasbp_invasive_max  :  0
d1_diasbp_invasive_min  :  0
d1_diasbp_max  :  0
d1_diasbp_min  :  0
d1_diasbp_noninvasive_max  :  0
d1_diasbp_noninvasive_min  :  0
d1_heartrate_max  :  0
d1_heartrate_min  :  0
d1_mbp_invasive_max  :  0
d1_mbp_invasive_min  :  0
d1_mbp_max  :  0
d1_mbp_min  :  0
d1_mbp_noninvasive_max  :  0
d1_mbp_noninvasive_min  :  0
d1_resprate_max  :  0
d1_resprate_min  :  0
d1_spo2_max  :  0
d1_spo2_min  :  0
d1_sysbp_invasive_max  :  0
d1_sysbp_invasive_min  :  0
d1_sysbp_max  :  0
d1_sysbp_min  :  0
d1_sysbp_noninvasive_max  :  0
d1_sysbp_noninvasive_min  :  0
d1_temp_max  :  0
d1_temp_min  :  0
h1_diasbp_invasive_max  :  0
h1_diasbp_invasive_min  :  0
h1_diasbp_max  :  0
h1_diasbp_min  :  0
h1_diasbp_noninvasive_max  :  0
h1_diasbp_noninvasive_min  :  0
h1_heartrate_max  :  0
h1_heartrate_min  :  0
h1_mbp_invasive_max  :  0
h1_mbp_invasive_min  :  0
h1_mbp_max  :  0
h1_mbp_min  :  0
h1_mbp_noninvasive_max  :  0
h1_mbp_noninvasive_min  :  0
h1_resprate_max  :  0
h1_resprate_min  :  0
h1_spo2_max  :  0
h1_spo2_min  :  0
h1_sysbp_invasive_max  :  0
h1_sysbp_invasive_min  :  0
h1_sysbp_max  :  0
h1_sysbp_min  :  0
h1_sysbp_noninvasive_max  :  0
h1_sysbp_noninvasive_min  :  0
h1_temp_max  :  0
h1_temp_min  :  0
d1_albumin_max  :  0
d1_albumin_min  :  0
d1_bilirubin_max  :  0
d1_bilirubin_min  :  0
d1_bun_max  :  0
d1_bun_min  :  0
d1_calcium_max  :  0
d1_calcium_min  :  0
d1_creatinine_max  :  0
d1_creatinine_min  :  0
d1_glucose_max  :  0
d1_glucose_min  :  0
d1_hco3_max  :  0
d1_hco3_min  :  0
d1_hemaglobin_max  :  0
d1_hemaglobin_min  :  0
d1_hematocrit_max  :  0
d1_hematocrit_min  :  0
d1_inr_max  :  0
d1_inr_min  :  0
d1_lactate_max  :  0
d1_lactate_min  :  0
d1_platelets_max  :  0
d1_platelets_min  :  0
d1_potassium_max  :  0
d1_potassium_min  :  0
d1_sodium_max  :  0
d1_sodium_min  :  0
d1_wbc_max  :  0
d1_wbc_min  :  0
h1_bun_max  :  0
h1_bun_min  :  0
h1_calcium_max  :  0
h1_calcium_min  :  0
h1_creatinine_max  :  0
h1_creatinine_min  :  0
h1_glucose_max  :  0
h1_glucose_min  :  0
h1_hco3_max  :  0
h1_hco3_min  :  0
h1_hemaglobin_max  :  0
h1_hemaglobin_min  :  0
h1_hematocrit_max  :  0
h1_hematocrit_min  :  0
h1_inr_max  :  0
h1_inr_min  :  0
h1_platelets_max  :  0
h1_platelets_min  :  0
h1_potassium_max  :  0
h1_potassium_min  :  0
h1_sodium_max  :  0
h1_sodium_min  :  0
h1_wbc_max  :  0
h1_wbc_min  :  0
d1_arterial_pco2_max  :  0
d1_arterial_pco2_min  :  0
d1_arterial_ph_max  :  0
d1_arterial_ph_min  :  0
d1_arterial_po2_max  :  0
d1_arterial_po2_min  :  0
d1_pao2fio2ratio_max  :  0
d1_pao2fio2ratio_min  :  0
h1_arterial_pco2_max  :  0
h1_arterial_pco2_min  :  0
h1_arterial_ph_max  :  0
h1_arterial_ph_min  :  0
h1_arterial_po2_max  :  0
h1_arterial_po2_min  :  0
h1_pao2fio2ratio_max  :  0
h1_pao2fio2ratio_min  :  0
apache_4a_hospital_death_prob  :  0
apache_4a_icu_death_prob  :  0
aids  :  0
cirrhosis  :  0
diabetes_mellitus  :  0
hepatic_failure  :  0
immunosuppression  :  0
leukemia  :  0
lymphoma  :  0
solid_tumor_with_metastasis  :  0
body_mass_index  :  0
body_mass_index:<15  :  0
body_mass_index:>15 and <=16  :  0
body_mass_index:>16 and <=19  :  0
body_mass_index:>19 and <=25  :  0
body_mass_index:>25 and <=30  :  0
body_mass_index:>30 and <=35  :  0
body_mass_index:>35 and <=40  :  0
body_mass_index:>40  :  0
IsUrgent  :  0
max_apache_4a_death_prob  :  0
ethnicity_Asian  :  0
ethnicity_Caucasian  :  0
ethnicity_Hispanic  :  0
ethnicity_Native American  :  0
ethnicity_Other/Unknown  :  0
gender_M  :  0
icu_stay_type_readmit  :  0
icu_stay_type_transfer  :  0
icu_admit_source_Floor  :  0
icu_admit_source_Operating Room / Recovery  :  0
icu_admit_source_Other Hospital  :  0
icu_admit_source_Other ICU  :  0
icu_type_CSICU  :  0
icu_type_CTICU  :  0
icu_type_Cardiac ICU  :  0
icu_type_MICU  :  0
icu_type_Med-Surg ICU  :  0
icu_type_Neuro ICU  :  0
icu_type_SICU  :  0
apache_2_bodysystem_Gastrointestinal  :  0
apache_2_bodysystem_Haematologic  :  0
apache_2_bodysystem_Metabolic  :  0
apache_2_bodysystem_Neurologic  :  0
apache_2_bodysystem_Renal/Genitourinary  :  0
apache_2_bodysystem_Respiratory  :  0
apache_2_bodysystem_Trauma  :  0
apache_2_bodysystem_Undefined Diagnoses  :  0
apache_2_bodysystem_Undefined diagnoses  :  0
apache_3j_bodysystem_Gastrointestinal  :  0
apache_3j_bodysystem_Genitourinary  :  0
apache_3j_bodysystem_Gynecological  :  0
apache_3j_bodysystem_Hematological  :  0
apache_3j_bodysystem_Metabolic  :  0
apache_3j_bodysystem_Musculoskeletal/Skin  :  0
apache_3j_bodysystem_Neurological  :  0
apache_3j_bodysystem_Respiratory  :  0
apache_3j_bodysystem_Sepsis  :  0
apache_3j_bodysystem_Trauma  :  0
hospital_admit_source_Chest Pain Center  :  0
hospital_admit_source_Direct Admit  :  0
hospital_admit_source_Emergency Department  :  0
hospital_admit_source_Floor  :  0
hospital_admit_source_ICU  :  0
hospital_admit_source_ICU to SDU  :  0
hospital_admit_source_Observation  :  0
hospital_admit_source_Operating Room  :  0
hospital_admit_source_Other  :  0
hospital_admit_source_Other Hospital  :  0
hospital_admit_source_Other ICU  :  0
hospital_admit_source_PACU  :  0
hospital_admit_source_Recovery Room  :  0
hospital_admit_source_Step-Down Unit (SDU)  :  0

In [48]:
# Check the summary statistics for the final dataframe
data_save.describe()

,hospital_death,age,elective_surgery,height,readmission_status,albumin_apache,apache_2_diagnosis,apache_3j_diagnosis,apache_post_operative,arf_apache,...,hospital_admit_source_ICU,hospital_admit_source_ICU to SDU,hospital_admit_source_Observation,hospital_admit_source_Operating Room,hospital_admit_source_Other,hospital_admit_source_Other Hospital,hospital_admit_source_Other ICU,hospital_admit_source_PACU,hospital_admit_source_Recovery Room,hospital_admit_source_Step-Down Unit (SDU)
count,91713.000000,91713.000000,91713.000000,91713.000000,91713.0,91713.000000,91713.000000,91713.000000,91713.000000,91713.000000,...,91713.000000,91713.000000,91713.000000,91713.000000,91713.000000,91713.000000,91713.000000,91713.000000,91713.000000,91713.000000
mean,0.086302,62.433548,0.183736,169.648256,0.0,3.019793,184.089693,557.530103,0.201106,0.027761,...,0.000382,0.000491,0.000109,0.106713,0.000076,0.017893,0.002541,0.011089,0.031577,0.012332
std,0.280811,16.393595,0.387271,10.716719,0.0,0.445681,85.812818,460.519921,0.400829,0.164287,...,0.019532,0.022146,0.010442,0.308750,0.008736,0.132562,0.050340,0.104719,0.174871,0.110363
min,0.000000,16.000000,0.000000,137.200000,0.0,1.200000,101.000000,0.010000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,53.000000,0.000000,162.560000,0.0,3.100000,113.000000,203.010000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,65.000000,0.000000,170.100000,0.0,3.100000,122.000000,410.010000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,75.000000,0.000000,177.800000,0.0,3.100000,301.000000,703.030000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,89.000000,1.000000,195.590000,0.0,4.600000,308.000000,2201.050000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [50]:
# Save data 
data_save.to_pickle('./dataset/data90.pkl')